channels:
  - conda-forge
  - defaults
dependencies:
  - astropy==5.1
  - cfunits=3.3.4
  - ephem==4.1.3
  - h5py==3.7.0
  - jplephem=2.17
  - matplotlib==3.5.3
  - netcdf4==1.6.0
  - pandas==1.4.3
  - pydap=3.3.0
  - python=3.10.6
  - python-dateutil=2.8.2
  - requests=2.28.1
  - scipy==1.9.1
  - sgp4==2.21
  - skyfield=1.41
  - xarray=2022.6.0
  - sphinx
  - sphinx_rtd_theme=1.0
  - myst-parser
  - linkify-it-py
  - graphviz
